language: cpp

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-all-dev libfmt-dev

script: make && make test
