language: cpp
dist: trusty
sudo: false
os: linux

matrix:
  include:
    - env: COMPILER=g++-6 BUILD=Debug STANDARD=14
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6 libboost-all-dev
    - env: COMPILER=g++-6 BUILD=Release STANDARD=14
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test

          packages:
            - g++-6 libboost1.55--all-dev

before install:
  - sudo add-apt-repository ppa:boost-latest/ppa
  - sudo apt-get update
  - sudo apt-cache search libboost
  - sudo apt-get install libboost1.65-all-dev

before_script:
  - sudo apt-cache search libboost
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CXX=${COMPILER}; fi
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
