* monstar
A C++ library for MONitoring an application and sending data to grafana to generate STAtistics and Reporting.


** Purpose

   MONSTAR is a library I created to simplify monitoring C++
   applications using Grafana together with Elasticsearch and
   Graphite.

** Use Cases

   The easiest way to get started with MONSTAR is probably to work
   through the examples in the examples directory.

   Monstar currently supports three use cases:

   - In instant simple numeric information in Graphite.
   - In instant scope benchmarking.
   - Event based message transation to time-series data.  This
     currently only supports Elasticsearch data.


   The tutorial section below gives examples of implementing these
   three use cases.


** Warning:

   While I hope this is already useful for people, the project is not
   partiularly mature.  I am actively developing and testing the
   library, so the interface is subject to change, and there's
   probably a lot of errors and suboptimal stuff.  Feedbacck and pull
   requests are welcome!
